### ISSUE TITLE
procedure to compile and install

### ISSUE THREAD

**Issue by biswajitutil** [georgemakrakis/zeek-iec104#12]
Hi @georgemakrakis 

What is the recommended procedure to compile and install this spicy parser? I compile spicy analyzer separately and install iec104.hlto file manually to plugin folder and the use it with zeek.

Thanks
Biswa

**Comment by georgemakrakis** [comment]
@biswajitutil I think this can be now found in the [installation ](https://github.com/georgemakrakis/zeek-iec104#installation)section of the README.

**Comment by biswajitutil** [comment]
While using 
cmake .

I am getting spicyz error, although I have installed zeek and spicy in default /usr/local/zeek directory.
Can you add basic environment set before compiling in the installation doc?

[root@zeek zeek-iec104]# cmake .
-- spicyz: /usr/local/zeek/bin/spicyz
-- Zeek plugin version: 6.1.0
-- Zeek plugin CMake path: /usr/local/zeek/share/zeek/cmake
-- Found zeek-config: /usr/local/zeek/bin/zeek-config
-- Found Zeek: yes
-- cannot determine location of Spicy installation
CMake Error at /usr/local/zeek/share/zeek/cmake/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Spicy (missing: HAVE_SPICY SPICY_CONFIG)
Call Stack (most recent call first):
  /usr/local/zeek/share/zeek/cmake/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/zeek/share/zeek/cmake/FindSpicy.cmake:183 (find_package_handle_standard_args)
  cmake/FindSpicyPlugin.cmake:70 (find_package)
  CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!

Then I have added below to make it work, so you can add to set proper zeek path before starting compilation

export PATH=/usr/local/zeek/bin:$PATH



Thanks
