### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by IamTenacious** [georgemakrakis/zeek-iec104#16]
Hi,
I have installed this plugin and did not get any error during installation. To test the working of plugin I used the PCAPs provided in this repo but I do not see parsed logs and traffic in my system.
Where can I see the logs? and for errors if any. also how the parser works is there any other steps of using parser?
please reply soon.

**Comment by IamTenacious** [comment]
@georgemakrakis

**Comment by georgemakrakis** [comment]
Hi @IamTenacious apologies for the delayed response. Did you figure out a solution for this? If not, please feel free to reopen this issue and provide more information about how you run Zeek (e.g. command, deamon) and what do you as output (e.g. errors or successful Zeek output). 

When the parser has successfully identified IEC 104 packets. it produces a main ``iec104.log`` file  and for each ASDU type, a list of a corresponding log file is created e.g. ``M_SP_NA_1.log``. This process is described in the [README](https://github.com/georgemakrakis/zeek-iec104?tab=readme-ov-file#logging-capabilities)
