### ISSUE TITLE
service field empty in conn.log

### ISSUE THREAD

**Issue by ashish21222** [georgemakrakis/zeek-iec104#4]
Hi @georgemakrakis

I have tried multiple pcaps on the iec104 analyzer but when I check conn.log file it shows the `service` field as `-`. Also I wanted to understand why you have kept 

`on iec104::Packet::%done {
    zeek::confirm_protocol();
}
`

commented out as that would not enable the analyzer to be used from the script.

Thanks,
Ashish

**Comment by georgemakrakis** [comment]
Hello @ashish21222 , apologies for the delayed response.  I am new to creating Zeek and Spicy parsers. This is my first attempt in the world of Zeek development. I see that the services field is populated by the [known-services.zeek](https://docs.zeek.org/en/master/scripts/policy/protocols/conn/known-services.zeek.html#policy-protocols-conn-known-services-zeek), therefore I think that if IEC 104 does not exist there, that field cannot be populated.

As for the zeek::confirm_protocol();, based on the latest version of Spicy, it seems that this function is [deprecated](https://docs.zeek.org/projects/spicy/en/latest/zeek.html#controlling-zeek-from-spicy). I am not sure though what do you mean with "that would not enable the analyzer to be used from the script". I am  testing it by issuing the command: ```zeek -r <pcap_name> iec104.hlto ./scripts/main.zeek```

Let me know if the above help.

**Comment by georgemakrakis** [comment]
Closing that due to inactivity.
