### ISSUE TITLE
Entries of fields from previous info object types need to be cleared from the log

### ISSUE THREAD

**Issue by georgemakrakis** [georgemakrakis/zeek-iec104#6]
As the parsing and logging progresses the fields of previous info object types are also added to the logged record of the next ones. In an essence we need to re-init the Asdu in every event for those info object types and only log the fields that correspond to the info object type that is currently being parsed.

**Comment by biswajitutil** [comment]
Hi @georgemakrakis , 

Is this issue already fixed and merged?

**Comment by georgemakrakis** [comment]
@biswajitutil Yes that has been fixed in f42a1dd10e0c82bcca14f3927f11319e02db410c , thanks for pointing that out.
