### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by biswajitutil** [georgemakrakis/zeek-iec104#7]
Hi @georgemakrakis ,

Thanks for the iec104 parser. I was trying to run the script against available pcap and I am getting below error related to initialization. Is there any fix to these?

STARTDT con
TESTFR act
STARTDT con
TESTFR act
**1372919015.332997 error in <no location>: orphan field "value" in initialization ([Asdu_num=9, info_obj_addr=1, value=\x01, qds=[ov=0, bl=0, sb=0, nt=0, iv=0]])**
TESTFR act
TESTFR act
TESTFR act
TESTFR act
STARTDT act
**1372919022.839930 error in <no location>: orphan field "BSI" in initialization ([Asdu_num=1, info_obj_addr=3, BSI=[value=33554432]])
1372919022.845805 error in <no location>: orphan field "BSI" in initialization ([Asdu_num=2, info_obj_addr=3, BSI=[value=33554432]])**
TESTFR act
STARTDT act
**1372919023.042862 error in <no location>: orphan field "BSI" in initialization ([Asdu_num=3, info_obj_addr=3, BSI=[value=33554432]])**
TESTFR act
STARTDT con
TESTFR act
STARTDT con
**1372919024.448401 error in <no location>: orphan field "BSI" in initialization ([Asdu_num=4, info_obj_addr=14, BSI=[value=67108864]])
1372919024.600480 error in <no location>: orphan field "BSI" in initialization ([Asdu_num=5, info_obj_addr=14, BSI=[value=67108864]])**
TESTFR act
**1372919024.600480 error in <no location>: orphan field "BSI" in initialization ([Asdu_num=6, info_obj_addr=14, BSI=[value=67108864]])**

Thanks
Biswajit

**Comment by georgemakrakis** [comment]
Hello @biswajitutil 

Thanks for letting me know about this issue. Can you point me to the PCAP that you are using? Is it one from the traces that I include in the [repo](https://github.com/georgemakrakis/zeek-iec104/tree/main/testing/Traces) ?

**Comment by biswajitutil** [comment]
Yes, that one only, inside "first" folder, iec104.pcap.

**Comment by georgemakrakis** [comment]
@biswajitutil I think that this issue has been resolved now in commit eb6910eecefc6e054068e06549ed82c5a9dfadb4 . Can you please verify?

**Comment by biswajitutil** [comment]
@georgemakrakis I will check and let you know.

**Comment by georgemakrakis** [comment]
@biswajitutil Is it working for you now? If so I would like to close this issue.

**Comment by biswajitutil** [comment]
Hi @georgemakrakis , Sorry for late response, I have checked and it's working fine. Please close this issue.
