### ISSUE TITLE
Parsing completion event

### ISSUE THREAD

**Issue by biswajitutil** [georgemakrakis/zeek-iec104#8]
Hi @georgemakrakis ,
There are multiple events which will come to zeek script from spicy parser for a single packet/connection. I need to identify the last event which will tell "this is the end of the iec104 parsing". Which one should I use for that? Earlier I thought if connection remove event hits then I will get all parsed info for that connection but that will not be always available. The pcap we are testing from repo itself doesn't have connection removal event, so I am not able to identify the end of parisng for a connection/packet. Please comment.

Thanks.

**Comment by georgemakrakis** [comment]
@biswajitutil I do not think I understand the issue. Do you mean that the connection_state_remove event in [main.zeek](https://github.com/georgemakrakis/zeek-iec104/blob/main/scripts/main.zeek) should produce an output to the log file? Also not sure about your term **connection/packet**. IEC 104 is based on TCP and not UDP (connection oriented vs connectionless) so the connection and packet are two different things.

**Comment by biswajitutil** [comment]
@georgemakrakis , there are N number of events on which one can subscribe to get parsed data in main.zeek. I want an indication in terms of event which will tell OK, this is the last event which is generated after the completion of IEC104 packet or flow (yes, packet and flow are different). In general, we subscribe on connection remove event (here remove means when zeek deletes a connection/flow from its end, it generates one event) in main.zeek, from which we can dump one log output which will have all the aggregated fields from all the events passed for that connection/flow. Hope you understand the requirement. 
Thanks

**Comment by georgemakrakis** [comment]
@biswajitutil I am still not sure that I understand the issue. The final output of each individual log for now, is being produced a then end of the parsing of the PCAP. Probably the **connection_state_remove** event in the [main.zeek](https://github.com/georgemakrakis/zeek-iec104/blob/main/scripts/main.zeek) file should be used, but if the packet capture does not include a TCP connection termination I do not think that this it possible to know when the connection terminates.

May I ask the reason behind this request? It might help me to better understand the issue and potentially find a solution.

Can you also point me to the PCAP that you refer to? Is it the **20200608_UOWM_IEC104_Dataset_mitm_drop_iecserver1.pcap** from the [second](https://github.com/georgemakrakis/zeek-iec104/tree/main/testing/Traces/second) part of traces?

**Comment by biswajitutil** [comment]
Hi @georgemakrakis ,

you got it right , I want a similar event to connection_state_remove from iec104 parser itself. While we parse iec104 message , there must be something which is being parsed at last, so I was asking for any such iec104 event , connection state remove may or may not come instantly. So I don’t want to rely totally on this event and rather get an event from iec104 as an end of passing notification.

The requirement is to gather all parsed information of an iec104 packet from different iec104 events and then send it to a daemon over zeek broker framework for further analysis. 

Thanks 
Biswa

**Comment by biswajitutil** [comment]
Hi @georgemakrakis ,
Have you written similar parser for IEC61850 or MMS protocol which is also very widely used protocol. However, if not written or planned, can you please help me writing a simple parser for the same. I want a very basic spicy parser skeleton for iec61850 to start with. 
Thanks a lot! 
Regards,
Biswa

**Comment by georgemakrakis** [comment]
> Hi @georgemakrakis ,
> 
> you got it right , I want a similar event to connection_state_remove from iec104 parser itself. While we parse iec104 message , there must be something which is being parsed at last, so I was asking for any such iec104 event , connection state remove may or may not come instantly. So I don’t want to rely totally on this event and rather get an event from iec104 as an end of passing notification.
> 
> The requirement is to gather all parsed information of an iec104 packet from different iec104 events and then send it to a daemon over zeek broker framework for further analysis.
> 
> Thanks Biswa

I think I understand the situation better now. As it is, the parser logs each event when it is encountered (e.g. found in the PCAP) in the corresponding file.  Take for example the Single Command (SCO) event in [main.zeek](https://github.com/georgemakrakis/zeek-iec104/blob/c3ff906db0ce94ec5cbfdfe56db34c44500fb652/scripts/main.zeek#L1105). At the end of it, we write the parsed fields of the corresponding IEC 104 packet to a separate log file if the APCI is of type "I-format". Otherwise the "U-" and "S-format" are logged in the iec104.log.  In the above example for SCO, that file will be "iec104-SCO.log".

Now if you want to stream information to another process or system it might be possible to keep checking for these log files and as they are updated to read their contents. However, the last part goes beyond the context of this parse since it is custom system that you might use.

**Comment by georgemakrakis** [comment]
> Hi @georgemakrakis , Have you written similar parser for IEC61850 or MMS protocol which is also very widely used protocol. However, if not written or planned, can you please help me writing a simple parser for the same. I want a very basic spicy parser skeleton for iec61850 to start with. Thanks a lot! Regards, Biswa

In our research group, we have thought creating a parser for GOOSE since that we would have been a useful addition to our lab. However, we have not started this process yet since we got involved with other tasks. I am still not sure if a parser for GOOSE exists out there using Spicy, but as for "planned" (with design, acquiring/creating PCAPs) no, we have not started this process yet.

**Comment by biswajitutil** [comment]
@georgemakrakis ok , thanks for the info, I was talking about MMS which is more of COTP(ip based) , where as GOOSE is little different in terms of protocol handling (layer2/mac based/peer to peer). 
anyway I need a starting skeleton for MMS, which is very similar to IEC104 in terms of spicy parser. It will be great if you can provide a basic spicy parser for iec61850 MMS protocol. 

Thanks

**Comment by georgemakrakis** [comment]
For now, there is no plan for creating any IEC 61850-based protocols parsers. Let me know if the [above](https://github.com/georgemakrakis/zeek-iec104/issues/8#issuecomment-1791828301) works.

**Comment by georgemakrakis** [comment]
I assume that the above works, so will am closing the issue.
