### ISSUE TITLE
Getting "cannot coerce expression" error with this spicy version

### ISSUE THREAD

**Issue by biswajitutil** [georgemakrakis/zeek-iec104#9]
=== STDERR ===

====================|  Spicy-side Zeek Installation Summary  |====================

Found Zeek:            yes

Version:               6.0.0 (60000)
Prefix:                /usr/local/zeek
Build type:            relwithdebinfo

========================================================================

====================|  Spicy Installation Summary  |====================

Found Spicy:           yes

Version:               1.9.0-dev.157 (d26c81c0) (10900)
Prefix:                /mnt/zeek/broker
Build type:            release
Have toolchain:        yes
Spicy compiler:        /mnt/zeek/broker/bin/spicyc

========================================================================

[error] /mnt/zeek/broker/var/lib/zkg/testing/zeek-iec104/clones/zeek-iec104/analyzer/iec104.spicy:743:5: **cannot coerce expression** '(0, asdu.info_obj_addr, asdu.siq)' of type 'tuple<uint<64>, uint<64>, bitfield(8) {     spi: 0;     bl: 4;     sb: 5;     nt: 6;     iv: 7; }>' to type 'tuple<uint<64>, uint<64>, tuple<spi: uint<8>, bl: uint<8>, sb: uint<8>, nt: uint<8>, iv: uint<8>>>'
[error] /mnt/zeek/broker/var/lib/zkg/testing/zeek-iec104/clones/zeek-iec104/analyzer/iec104.spicy:747:5: **cannot coerce expression** '(0, asdu.info_obj_addr, asdu.sco)' of type 'tuple<uint<64>, uint<64>, bitfield(8) {     sco_on: 0;     qu: 2..6;     se: 7; }>' to type 'tuple<uint<64>, uint<64>, tuple<sco_on: uint<8>, qu: uint<8>, se: uint<8>>>'

Any idea how to fix this issue?

Thanks

**Comment by georgemakrakis** [comment]
@biswajitutil I am currently looking at it. Are running it against any of the PCAPs in [Traces](https://github.com/georgemakrakis/zeek-iec104/tree/main/testing/Traces)? If so, which one?

**Comment by biswajitutil** [comment]
Yes same pcaps. Surprisingly the issue is not coming when using below versions.

root# /usr/local/zeek/bin/spicyc -v
spicyc v1.8.1
root# /usr/local/zeek/bin/zeek -v
/usr/local/zeek/bin/zeek version 6.0.0


However, please see the reply from zeek community 

[error](https://community.zeek.org/t/cannot-coerce-expression-error-while-compiling-spicy-script/7227/2)

**Comment by georgemakrakis** [comment]
@biswajitutil that is interesting... Can you also point me to any resources on how do you install Zeek and Spicy with versions **6.0.0** and **1.9.0-dev.157** correspondingly?

**Comment by biswajitutil** [comment]
Actually, my system has both latest zeek installed from developer branch and zeek 6.0.0 as well. So, these spicy scripts only work if we use zeek 6.0.0 with the native spicy version comes with 6.0.0 i.e. v1.8.1. But if you use latest zeek-dev (with its current spicy version or zeek 6.0.0 and latest spicy version) you will get this error. That means this issue may be coming in the new spicy versions. However, zeek community suggests this should come before as well that means in 6.0.0 but I have never got this error earlier.

**Comment by georgemakrakis** [comment]
Working on it, with the current commit 6a5db79203be24ecddb8a14bdc2b6a711c416891 I get a Segmentation Fault, that I am trying to resolve.

**Comment by georgemakrakis** [comment]
@biswajitutil I think that the issue has now been resolved in commit [eb78de1](https://github.com/georgemakrakis/zeek-iec104/commit/eb78de1314e6848212f8635de599a7c8f8ade502). I have tested it with the following:
```
root@zeek-latest:/zeek-iec104# zeek -v
zeek version 6.1.0
root@zeek-latest:/zeek-iec104# spicyc -v 
spicyc v1.9.0 (7b8eff52)
```
 Can you please check out and let me know?

**Comment by biswajitutil** [comment]
I am getting below error while compiling the parser with zeek_iec104.spicy. Earlier I didn't get this issue. Can please check? Without zeek_iec104.spicy, parser is compiling fine.

`
[root@]# /mnt/zeek/broker/bin/spicyz -o iec104.hlto iec104/analyzer/iec104.evt iec104/analyzer/iec104.spicy iec104/analyzer/zeek_iec104.spicy
[error] iec104/analyzer/zeek_iec104.spicy:3:1: invalid character
[error] iec104/analyzer/zeek_iec104.spicy:4:20: invalid character
[error] iec104/analyzer/zeek_iec104.spicy:5:1: invalid character
`

#zeek_iec104.spicy
`
module Zeek_iec104;

import iec104;
import zeek;

on iec104::Apcis::%done {
    zeek::confirm_protocol();
}

on iec104::Apcis::%error {
    zeek::reject_protocol("error while parsing iec104");
}
`
Regards,
Biswa

**Comment by georgemakrakis** [comment]
@biswajitutil  I think that was a line ending issue, I have addressed it in https://github.com/georgemakrakis/zeek-iec104/commit/9fabd3fb03de7c32377fbede354357e5dc9b01e5. Please check it out at your end and let me know.

**Comment by biswajitutil** [comment]
Hi George,
Thanks, I will check the above issue resolution. As you have done lots of hands on with spicy parser, can you suggest a way to access protocol payload or pdus per packet basis. Requirement is to send whole payload of a protocol for eg. iec104 to a third party daemon/parser from zeek. Currently we are using tcp payload over 2404 as iec104, my requirement is to send/dump this per packet payload. There is an option in payload &eod, (tried &chunked &eod as well) but it waits for whole stream not per packet, if you know solution to access per packet payload for a protocol, please let me know.
Thanks
Biswa

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by georgemakrakis** [comment]
@biswajitutil Please open up another issue for the above, to keep track of the changes better.

**Comment by georgemakrakis** [comment]
@biswajitutil I assume that this is working properly now from what you mentioned in issue https://github.com/georgemakrakis/zeek-iec104/issues/13, so I am closing this issue.
